menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'bluesky', link: 'https://usky.app/profile/awanib.bsky.social'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Awani-Bapat-2'}
- {icon: 'linkedin', link: 'https://at.linkedin.com/in/awani-bapat-94301941?trk=public_profile_browsemap'}

contacts:
- {name: 'Awani Bapat', title: 'PhD Candidate', department: 'Behavioral & Cognitive Biology', institution: 'University of Vienna', institution_address: 'Djerassiplatz 1, A-1030 Vienna', email: 'awani.bapat@univie.ac.at', image: 'assets/img/contact.jpg'}
